name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install

      - name: Run Vitest and output JUnit report
        run: npm run vitest

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: vitest-junit-report
          path: doc.xml
