name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

      - name: Run Vitest and output JUnit report
        run: |
          npx vitest run \
            --reporter default \
            --reporter junit \
            --outputFile doc.xml

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: vitest-junit-report
          path: doc.xml
